name: First Workflow

on: push 

jobs: 
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
  

      - name: Commands 
        run: |
          echo "This is my first GH actions job"
          ls -ltra 
          cat README.md
 