on:
  pull_request:
        types:
        - opened

jobs:
  testing-action: 
    runs-on: ubuntu
    permissions:
      issues: write
      pull-requests: write 
    steps:
    - name: Checkout Repository 
      uses: actions/checkout@v3 

    - name: Post PR Comment 
      uses: ./
      with: 
        github-token: ${{ secrets.GITHUB_TOKEN }}
        giphy-api-key: ${{ secrets.GIPHY_API_KEY }}