# See notes Chatper-1.1.md 
name: 15-TriggerInputs

on:
    workflow_dispatch:
      inputs:
        run-tests:
          description: "Run tests?"
          type: boolean
          required: true
        test-type:
          description: "Type of tests to run"
          type: choice
          options:
            - unit
            - integration
            - all
        environment: 
            description: "Environment to run in"
            type: environment
            required: true
        build-number:
            description: "Custom build number"
            type: number
            required: false
        message:
            description: "Additional message"
            type: string
            required: false 
jobs:
    build-and-debug:
        runs-on: ubuntu-latest
        steps:
            # Get inputs for dispatch
            - name: Print workflow inputs
              run: |
                echo "Run tests: ${{ inputs.run-tests }}" 
                echo "Test type: ${{ inputs.test-type }}"
                echo "Environment: ${{ inputs.environment }}"
                echo "1. AWS Account Number (from environment var): ${{ vars.AWS_ACCOUNT_NUMBER }}"
                echo "2. AWS Account Number (from environment var): ${{ env.AWS_ACCOUNT_NUMBER }}"
                echo "3. AWS Account Number (from environment var): ${{ secrets.AWS_ACCOUNT_NUMBER }}"
                echo "4. AWS Account Number (from environment var): ${{ inputs.environment.vars.AWS_ACCOUNT_NUMBER }}"
                echo "5. AWS Account Number (from environment var): ${{ inputs.environment.env.AWS_ACCOUNT_NUMBER }}"
                echo "6. AWS Account Number (from environment var): ${{ inputs.environment.AWS_ACCOUNT_NUMBER }}"
                echo "Build: ${{ inputs.build-number }}"
                echo "Message: ${{ inputs.message }}"
            
            # Comparing a boolean to a string will give FALSE in the below example!     
            # - name: Run tests (if selected)
            #   if: ${{ inputs.run-tests == 'true' }}
            #   run: echo "Testing..........."

            - name: Run tests (if selected)
              if: ${{ inputs.run-tests == true }}
              run: echo "Testing..........."  