name: 11-Matrix Configuration

on: workflow_dispatch

jobs:
    deploy:        
        strategy: 
              matrix:
                images: [amd64/alpine, alpine]
                os: [ubuntu-latest, macos-latest] 
        runs-on: ${{ matrix.os }}        
        steps:
        - name: Echo docker details 
          run: docker info 

        - name: Run images 
          run: docker run ${{ matrix.images }}
