# See chapter-1.1.md notes
name: 14-Workflow-Filters-Activities
on: 
  workflow_dispatch:
#   schedule:
#     - cron: "*/59 * * * *"
#   push: 
#     branches: 
#         - main
#         - '!feature/*' # ignore breanches beginning with !feature
    # branches-ignore:
    #     - feature/*
    #     - test/** 
  pull_request: 
    types:
        - opened
        - closed
    paths-ignore:
        - README.md
        - Notes/*
    branches:
        - main
jobs:
    hello:
        runs-on: ubunut-latest
        steps:
        - run: echo this workflow/job/step is executed for event type - ${{ github.event_name}}