# STUFF 
# CX Documentation: https://coralogix.com/docs/developer-portal/apis/version-tags/curl-version-tags/#support

name: Coralogix Inject Version Tags
on :
  workflow_call:
    inputs:
      name:
        description: 'Name' 
        required: true
        type: string
      application:
        description: 'Application'
        required: true
        type: string
      subsystem:
        description: 'Subsystem'
        required: true
        type: string
      cx_version_benchmark_url: 
        description: 'URL for Coralogix Benchmark Version'
        required: true 
        type: string
    secrets:
      cx_version_benchmark_api_key: 
        description: 'Coralogix Benchmark API Key'
        required: true
    
jobs:
  setup_vars:
    runs-on: ubuntu-latest
    outputs:
        sanitized_name: ${{ steps.sanitize.outputs.sanitized_name }}
        sanitized_application: ${{ steps.sanitize.outputs.sanitized_application }}
        sanitized_subsystem: ${{ steps.sanitize.outputs.sanitized_subsystem }}
    steps:
    - name: Check Environment Variables
      run: |
        if [[ -z "${{ inputs.cx_version_benchmark_url }}" ]]; then 
            echo "EROOR: Environment variable [[ cx_version_benchmark_url ]]"
            exit 44
        elif [[ -z "${{ secrets.cx_version_benchmark_api_key }}" ]]; then
            echo "ERROR: Environment secret [[ cx_version_benchmark_api_key ]] is not set."
            exit 55
        fi
    - name: Sanitize Passed Variables 
      id: sanitize
      run: |
        sanitize_input() {
            echo "$1" | tr -d '[:space:]' | tr -cd '[:alnum:]-_'
        }

        sanitized_name=$(sanitize_input "${{ inputs.name }}")
        sanitized_application=$(sanitize_input "${{ inputs.application }}")
        sanitized_subsystem=$(sanitize_input "${{ inputs.subsystem }}")

        # Output the values to $GITHUB_OUTPUT
        echo "sanitized_name=v$sanitized_name" >> "$GITHUB_OUTPUT"
        echo "sanitized_application=$sanitized_application" >> "$GITHUB_OUTPUT"
        echo "sanitized_subsystem=$sanitized_subsystem" >> "$GITHUB_OUTPUT"

  curl_request:    
    runs-on: ubuntu-latest     
    needs: setup_vars
    steps:
      - name: Send POST Request
        id: post-request
        env:
            SANITIZED_NAME: ${{ needs.job1.outputs.sanitized_name }}
            SANITIZED_APPLICATION: ${{ needs.job1.outputs.sanitized_application }}
            SANITIZED_SUBSYSTEM: ${{ needs.job1.outputs.sanitized_subsystem }}
        run: |
          response=$(curl -s -o response.txt -w "%{http_code}" \
          --location \
          --request POST "${{ inputs.cx_version_benchmark_url }}" \
          --header "Content-Type: application/json" \
          --data-raw '{
            "name": "${{ env.SANITIZED_NAME }}",
            "application": ["${{ env.SANITIZED_APPLICATION }}"],
            "subsystem": ["${{ env.SANITIZED_SUBSYSTEM }}"],
            "key": ["${{ secrets.cx_version_benchmark_api_key }}"]
          }')

          if [[ "$response" -ne 200 ]]; then
            echo "Error: Received HTTP status code $response"
            cat response.txt
            exit 30
          fi

          echo "Request successful. Response:"
          cat response.txt
