name: Coralogix Inject Version Tags
on:
  workflow_push:
    inputs:
      name:
        description: 'Name'
        required: true
        type: string
      application:
        description: 'Application'
        required: true
        type: string
      subsystem:
        description: 'Subsystem'
        required: true
        type: string
      cx_version_benchmark_url:
        description: 'URL for Coralogix Benchmark Version'
        required: true
        type: string
      cx_version_benchmark_api_key:
        description: 'Coralogix Benchmark API Key'
        required: true
        type: string
        # Note: Secrets cannot be directly defined in the inputs section.
jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use API Key
        run: echo "Using API Key"
        env:
          CX_VERSION_BENCHMARK_API_KEY: ${{ secrets.CX_VERSION_BENCHMARK_API_KEY }}

      - name: Echo it to see if it shows up or not 
        run: | 
          echo " Here is the var: ${{ secrets.CX_VERSION_BENCHMARK_API_KEY }}" "