name: Testing Getting Env Vars to Work 
on: workflow_dispatch

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag
        run: echo "IMAGE_TAG=$(echo hello)" >> "$GITHUB_ENV"

      - name: Echo tag
        run: |
             echo "Extracted tag 1: $IMAGE_TAG"
        # env:
        #   IMAGE_TAG: ${{ env.IMAGE_TAG }}
