name: Test installed packages

on:  workflow_dispatch

jobs:
  upload-to-dev-and-qa:
    runs-on: ubuntu-latest

    steps:
    - name: Make fake files 
      run: |
        touch epesystem-1.tar.gz
        touch epesystem-2.tar.gz
        touch epesystem-3.tar.gz

    - name: Load Docker File
      run: |
        latest=$(find . -name "epesystem*.tar.gz" -type f -exec stat --format="%Y %n" {} \; | sort -n | tail -1 | cut -d' ' -f2-)

        base_name=$(basename "$latest")
        echo $base_name
    