name: Test Workflow Dispatch

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message to display'
        required: true
        default: 'Hello, World!'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Display message
      run: echo "${{ inputs.message }}"
